dist: xenial
# dist: trusty works only up to 3.6

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

addons:
  sonarcloud:
    organization: "dereklm12880"
    token: $SONAR_TOKEN

script:
    - sonar-scanner