dist: 

language: python

matrix:
  include:
    python: 3.6
    dist: xenial
    env: python=python3
    python: 3.7
    dist: xenial
    env: python=python3
    python: 3.8
    dist: trusty
    env: python=python3

addons:
  sonarcloud:
    organization: "dereklm12880"
    token: $SONAR_TOKEN

script:
    - sonar-scanner